import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header/Header";
import { Toaster } from "@/components/ui/toaster";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`antialiased`}>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <Toaster />
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
